version: '3.7'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "20448273"
      TELEGRAM_API_HASH: "25a0ad7791e66b9f53d79c52178ec358"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - 8082:8081

volumes:
  telegram-bot-api-data: