apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.controller.type: deployment
    kompose.service.nodeport.port: "30015"
    kompose.service.type: nodeport
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: tdlight-tdlightbotapi
  name: tdlight-tdlightbotapi
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: tdlight-tdlightbotapi
  type: NodePort
status:
  loadBalancer: {}
